# Generated by Django 3.0.3 on 2020-04-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='hash',
            new_name='hash_patient',
        ),
    ]
