# Generated by Django 3.0.3 on 2020-04-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200404_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='hash_patient',
            field=models.CharField(max_length=60),
        ),
    ]
