# Generated by Django 3.0.5 on 2020-04-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200404_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='salt',
            field=models.CharField(max_length=36),
            preserve_default=False,
        ),
    ]
