# Generated by Django 3.0.3 on 2020-04-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200404_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=15)),
                ('executed_at', models.DateField(verbose_name='day month and year the test was executed')),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
