# Generated by Django 3.0.3 on 2020-04-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_resultrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultrequest',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
